import turtle
turtle.showturtle()
turtle.write("Joana Mucogllava")
turtle.forward(100)
turtle.right(90)
turtle.color("blue")
turtle.forward(50)
turtle.right(90)
turtle.color("purple")
turtle.forward(100)
turtle.right(45)
turtle.forward(80)
